# Generated by Django 2.0.7 on 2018-08-21 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180821_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('access_dashboard', '控制面板'), ('access_log', '日志管理'), ('access_role_manage', '角色管理'), ('access_user_manage', '用户管理')),
            },
        ),
        migrations.AlterField(
            model_name='dialog',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('0eccebd1-459c-408b-aaf2-3ab0ac503d1a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
