# Generated by Django 2.0.7 on 2018-08-21 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180821_0705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessControl',
        ),
        migrations.AlterField(
            model_name='dialog',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('2428d489-b1e5-47ba-ab21-709dfee6ef4e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
