# Generated by Django 2.0.7 on 2018-07-24 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('cname', models.CharField(max_length=10, null=True, unique=True, verbose_name='课程')),
                ('score', models.IntegerField(null=True, verbose_name='成绩')),
                ('creater', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('name', models.CharField(max_length=10, null=True, unique=True, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=30, null=True, unique=True, verbose_name='电话')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('creater', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('Id', models.UUIDField(default=uuid.UUID('d911ec3f-3579-4132-81c8-5d3ff7d4eed2'), editable=False, primary_key=True, serialize=False)),
                ('Callee', models.CharField(default='', max_length=15, verbose_name='被叫号码')),
                ('BeginTime', models.DateTimeField(default=None, verbose_name='开始时间')),
                ('EndTime', models.DateTimeField(default=None, verbose_name='结束时间')),
                ('BillTime', models.IntegerField(default=0, verbose_name='计费时长')),
                ('Duration', models.IntegerField(default=0, verbose_name='通话时长')),
                ('StartTime', models.DateTimeField(default=None, verbose_name='拨打时间')),
                ('CloseTime', models.DateTimeField(default=None, verbose_name='挂断时间')),
                ('RecordFile', models.FileField(blank=True, null=True, upload_to='dialogRecord', verbose_name='对话录音文件')),
                ('RecordContextFile', models.FileField(blank=True, null=True, upload_to='dialogContext', verbose_name='对话内容文件')),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('Creater', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_creater', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
