# Generated by Django 2.0.5 on 2018-06-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.IntegerField(max_length=3, null=True, unique=True, verbose_name='成绩'),
        ),
    ]
