# Generated by Django 2.0.7 on 2018-08-21 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180821_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessControl',
        ),
        migrations.AlterField(
            model_name='dialog',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('a346cb0d-4ae3-411f-8fd8-993263e57492'), editable=False, primary_key=True, serialize=False),
        ),
    ]
