# Generated by Django 2.0.7 on 2018-08-21 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180821_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscontrol',
            options={'permissions': (('access_role_manage', 'role'),)},
        ),
        migrations.AlterField(
            model_name='dialog',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('63987b54-4e58-44b8-9003-2951ede35a3f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
